/*
 * Health Facility Registry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.api.phr;

import com.google.gson.reflect.TypeToken;
import in.docq.abha.rest.client.*;
import in.docq.abha.rest.client.model.*;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OnboardingApisApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OnboardingApisApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OnboardingApisApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v15BasicFacilityInformation
     * @param xHpridAuth  (required)
     * @param authorization  (optional)
     * @param facilityBasicInformationRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v15BasicFacilityInformationCall(String xHpridAuth, String authorization, FacilityBasicInformationRequest facilityBasicInformationRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = facilityBasicInformationRequest;

        // create path and map variables
        String localVarPath = "/v1.5/facility/basic-information";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        if (xHpridAuth != null) {
            localVarHeaderParams.put("x-hprid-auth", localVarApiClient.parameterToString(xHpridAuth));
        }


        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v15BasicFacilityInformationValidateBeforeCall(String xHpridAuth, String authorization, FacilityBasicInformationRequest facilityBasicInformationRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xHpridAuth' is set
        if (xHpridAuth == null) {
            throw new ApiException("Missing the required parameter 'xHpridAuth' when calling v15BasicFacilityInformation(Async)");
        }

        return v15BasicFacilityInformationCall(xHpridAuth, authorization, facilityBasicInformationRequest, _callback);

    }

    /**
     * 
     * 
     * @param xHpridAuth  (required)
     * @param authorization  (optional)
     * @param facilityBasicInformationRequest  (optional)
     * @return FacilityOnboardResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public FacilityOnboardResponse v15BasicFacilityInformation(String xHpridAuth, String authorization, FacilityBasicInformationRequest facilityBasicInformationRequest) throws ApiException {
        ApiResponse<FacilityOnboardResponse> localVarResp = v15BasicFacilityInformationWithHttpInfo(xHpridAuth, authorization, facilityBasicInformationRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param xHpridAuth  (required)
     * @param authorization  (optional)
     * @param facilityBasicInformationRequest  (optional)
     * @return ApiResponse&lt;FacilityOnboardResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FacilityOnboardResponse> v15BasicFacilityInformationWithHttpInfo(String xHpridAuth, String authorization, FacilityBasicInformationRequest facilityBasicInformationRequest) throws ApiException {
        okhttp3.Call localVarCall = v15BasicFacilityInformationValidateBeforeCall(xHpridAuth, authorization, facilityBasicInformationRequest, null);
        Type localVarReturnType = new TypeToken<FacilityOnboardResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param xHpridAuth  (required)
     * @param authorization  (optional)
     * @param facilityBasicInformationRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v15BasicFacilityInformationAsync(String xHpridAuth, String authorization, FacilityBasicInformationRequest facilityBasicInformationRequest, final ApiCallback<FacilityOnboardResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = v15BasicFacilityInformationValidateBeforeCall(xHpridAuth, authorization, facilityBasicInformationRequest, _callback);
        Type localVarReturnType = new TypeToken<FacilityOnboardResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v15FacilityAdditionalInformation
     * @param authorization  (optional)
     * @param facilityAdditionalInformationRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v15FacilityAdditionalInformationCall(String authorization, FacilityAdditionalInformationRequest facilityAdditionalInformationRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = facilityAdditionalInformationRequest;

        // create path and map variables
        String localVarPath = "/v1.5/facility/additional-information";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v15FacilityAdditionalInformationValidateBeforeCall(String authorization, FacilityAdditionalInformationRequest facilityAdditionalInformationRequest, final ApiCallback _callback) throws ApiException {
        return v15FacilityAdditionalInformationCall(authorization, facilityAdditionalInformationRequest, _callback);

    }

    /**
     * 
     * 
     * @param authorization  (optional)
     * @param facilityAdditionalInformationRequest  (optional)
     * @return FacilityOnboardResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public FacilityOnboardResponse v15FacilityAdditionalInformation(String authorization, FacilityAdditionalInformationRequest facilityAdditionalInformationRequest) throws ApiException {
        ApiResponse<FacilityOnboardResponse> localVarResp = v15FacilityAdditionalInformationWithHttpInfo(authorization, facilityAdditionalInformationRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param authorization  (optional)
     * @param facilityAdditionalInformationRequest  (optional)
     * @return ApiResponse&lt;FacilityOnboardResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FacilityOnboardResponse> v15FacilityAdditionalInformationWithHttpInfo(String authorization, FacilityAdditionalInformationRequest facilityAdditionalInformationRequest) throws ApiException {
        okhttp3.Call localVarCall = v15FacilityAdditionalInformationValidateBeforeCall(authorization, facilityAdditionalInformationRequest, null);
        Type localVarReturnType = new TypeToken<FacilityOnboardResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param authorization  (optional)
     * @param facilityAdditionalInformationRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v15FacilityAdditionalInformationAsync(String authorization, FacilityAdditionalInformationRequest facilityAdditionalInformationRequest, final ApiCallback<FacilityOnboardResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = v15FacilityAdditionalInformationValidateBeforeCall(authorization, facilityAdditionalInformationRequest, _callback);
        Type localVarReturnType = new TypeToken<FacilityOnboardResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v15FacilityDetailedInformation
     * @param facilityDetailedInformationRequest  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v15FacilityDetailedInformationCall(FacilityDetailedInformationRequest facilityDetailedInformationRequest, String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = facilityDetailedInformationRequest;

        // create path and map variables
        String localVarPath = "/v1.5/facility/detailed-information";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v15FacilityDetailedInformationValidateBeforeCall(FacilityDetailedInformationRequest facilityDetailedInformationRequest, String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'facilityDetailedInformationRequest' is set
        if (facilityDetailedInformationRequest == null) {
            throw new ApiException("Missing the required parameter 'facilityDetailedInformationRequest' when calling v15FacilityDetailedInformation(Async)");
        }

        return v15FacilityDetailedInformationCall(facilityDetailedInformationRequest, authorization, _callback);

    }

    /**
     * 
     * 
     * @param facilityDetailedInformationRequest  (required)
     * @param authorization  (optional)
     * @return FacilityOnboardResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public FacilityOnboardResponse v15FacilityDetailedInformation(FacilityDetailedInformationRequest facilityDetailedInformationRequest, String authorization) throws ApiException {
        ApiResponse<FacilityOnboardResponse> localVarResp = v15FacilityDetailedInformationWithHttpInfo(facilityDetailedInformationRequest, authorization);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param facilityDetailedInformationRequest  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;FacilityOnboardResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FacilityOnboardResponse> v15FacilityDetailedInformationWithHttpInfo(FacilityDetailedInformationRequest facilityDetailedInformationRequest, String authorization) throws ApiException {
        okhttp3.Call localVarCall = v15FacilityDetailedInformationValidateBeforeCall(facilityDetailedInformationRequest, authorization, null);
        Type localVarReturnType = new TypeToken<FacilityOnboardResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param facilityDetailedInformationRequest  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v15FacilityDetailedInformationAsync(FacilityDetailedInformationRequest facilityDetailedInformationRequest, String authorization, final ApiCallback<FacilityOnboardResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = v15FacilityDetailedInformationValidateBeforeCall(facilityDetailedInformationRequest, authorization, _callback);
        Type localVarReturnType = new TypeToken<FacilityOnboardResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v15SubmitFacilityDetails
     * @param xHpridAuth  (required)
     * @param authorization  (optional)
     * @param xHpridAuthVerifier  (optional)
     * @param facilitySubmitDetails  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v15SubmitFacilityDetailsCall(String xHpridAuth, String authorization, String xHpridAuthVerifier, FacilitySubmitDetails facilitySubmitDetails, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = facilitySubmitDetails;

        // create path and map variables
        String localVarPath = "/v1.5/facility/submit-facility";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        if (xHpridAuth != null) {
            localVarHeaderParams.put("x-hprid-auth", localVarApiClient.parameterToString(xHpridAuth));
        }


        if (xHpridAuthVerifier != null) {
            localVarHeaderParams.put("x-hprid-auth-verifier", localVarApiClient.parameterToString(xHpridAuthVerifier));
        }


        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v15SubmitFacilityDetailsValidateBeforeCall(String xHpridAuth, String authorization, String xHpridAuthVerifier, FacilitySubmitDetails facilitySubmitDetails, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xHpridAuth' is set
        if (xHpridAuth == null) {
            throw new ApiException("Missing the required parameter 'xHpridAuth' when calling v15SubmitFacilityDetails(Async)");
        }

        return v15SubmitFacilityDetailsCall(xHpridAuth, authorization, xHpridAuthVerifier, facilitySubmitDetails, _callback);

    }

    /**
     * 
     * 
     * @param xHpridAuth  (required)
     * @param authorization  (optional)
     * @param xHpridAuthVerifier  (optional)
     * @param facilitySubmitDetails  (optional)
     * @return FacilitySubmitResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public FacilitySubmitResponse v15SubmitFacilityDetails(String xHpridAuth, String authorization, String xHpridAuthVerifier, FacilitySubmitDetails facilitySubmitDetails) throws ApiException {
        ApiResponse<FacilitySubmitResponse> localVarResp = v15SubmitFacilityDetailsWithHttpInfo(xHpridAuth, authorization, xHpridAuthVerifier, facilitySubmitDetails);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param xHpridAuth  (required)
     * @param authorization  (optional)
     * @param xHpridAuthVerifier  (optional)
     * @param facilitySubmitDetails  (optional)
     * @return ApiResponse&lt;FacilitySubmitResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FacilitySubmitResponse> v15SubmitFacilityDetailsWithHttpInfo(String xHpridAuth, String authorization, String xHpridAuthVerifier, FacilitySubmitDetails facilitySubmitDetails) throws ApiException {
        okhttp3.Call localVarCall = v15SubmitFacilityDetailsValidateBeforeCall(xHpridAuth, authorization, xHpridAuthVerifier, facilitySubmitDetails, null);
        Type localVarReturnType = new TypeToken<FacilitySubmitResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param xHpridAuth  (required)
     * @param authorization  (optional)
     * @param xHpridAuthVerifier  (optional)
     * @param facilitySubmitDetails  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v15SubmitFacilityDetailsAsync(String xHpridAuth, String authorization, String xHpridAuthVerifier, FacilitySubmitDetails facilitySubmitDetails, final ApiCallback<FacilitySubmitResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = v15SubmitFacilityDetailsValidateBeforeCall(xHpridAuth, authorization, xHpridAuthVerifier, facilitySubmitDetails, _callback);
        Type localVarReturnType = new TypeToken<FacilitySubmitResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
