management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99,0.999
  endpoints:
    prometheus:
      enabled: true
    web:
      base-path: /
      exposure:
        include: health,prometheus
      path-mapping:
        health: '/health'

spring:
  application:
    name: patient-service
  profiles:
    active: ${environmentName:local}
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    converters:
      preferred-json-mapper: gson
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  output:
    ansi:
      enabled: ALWAYS
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /

abha:
  client:
    id: SBXID_009458
    secret: c6d412fd-0eae-427a-8707-80d6327cf242
  base:
    url: https://dev.abdm.gov.in

keycloak:
  realm: health-facility
  jwks:
    cert: /realms/health-facility/protocol/openid-connect/certs
  base:
    url: http://localhost:8080
  backend:
    client:
      id: patient-backend-app
      secret: 90R4KlaDowq4jU5gM2g05BsBmDRPdW4f
  desktop:
    client:
      id: patient-mobile-app
      secret: 1OadpENrgZprruUrOOy014AoiNfu3jom
  patient:
    admin:
      username: patient-backend-app
      password: Kx9#mP2$vL8@nQ5!
  http:
    max:
      idle:
        connections: 20
    keep:
      alive:
        duration:
          minutes: 60
    timeout:
      seconds: 20
server:
  port: 9098

health-facility:
  service:
    url: http://localhost:9097

x:
  cm:
    id: sbx