management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99,0.999
  endpoints:
    prometheus:
      enabled: true
    web:
      base-path: /
      exposure:
        include: health,prometheus
      path-mapping:
        health: '/health'

spring:
  application:
    name: health-facility
  profiles:
    active: ${environmentName:local}
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  main:
    allow-bean-definition-overriding: true
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/health_facility
    username: docq
    password: docq
    driver: 'org.postgresql.Driver'
    poolSize: 20
    timeout: 2000
    hikari:
      pool-name: Hikari
      connection-timeout: 2000
      maximum-pool-size: 20
      auto-commit: false
      connection-test-query: select 1
      idle-timeout: 90000


  output:
    ansi:
      enabled: ALWAYS
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /

abha:
  client:
    id: SBXID_009458
    secret: c6d412fd-0eae-427a-8707-80d6327cf242
  base:
    url: https://dev.abdm.gov.in

keycloak:
  realm: health-facility
  jwks:
    cert: /realms/health-facility/protocol/openid-connect/certs
  base:
    url: http://localhost:8080
  backend:
    client:
      id: health-facility-backend-app
      secret: 9LLx9iKagI6GrDJ0zv5PAfn8mxHiM1DZ
  desktop:
    client:
      id: health-facility-desktop-app
      secret: erzn9h4oZCDFJKf7tobAx5OpzOR6ZIfe
  http:
    max:
      idle:
        connections: 20
    keep:
      alive:
        duration:
          minutes: 60
    timeout:
      seconds: 20
server:
  port: 9097

encryption:
  aes:
    key: vHEyVZcMpQZx+7O2bQ0eUwqTY1AvXg8Whq2mDJK6ClU=