/*
 * User Initiated Linking Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model.phr;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-12T17:25:36.087359+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner {
  public static final String SERIALIZED_NAME_REFERENCE_NUMBER = "referenceNumber";
  @SerializedName(SERIALIZED_NAME_REFERENCE_NUMBER)
  @javax.annotation.Nonnull
  private String referenceNumber;

  public static final String SERIALIZED_NAME_DISPLAY = "display";
  @SerializedName(SERIALIZED_NAME_DISPLAY)
  @javax.annotation.Nullable
  private String display;

  public AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner() {
  }

  public AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner referenceNumber(@javax.annotation.Nonnull String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

  /**
   * An identifier of patient&#39;s care context created in HIP. A care context is a group of patient&#39;s health data (Not the actual health data).Allows alpha numeric characters and special characters like \&quot;^[a-zA-Z0-9_\\\\-@,. ()/:\\\\\\\\]{0,255}$\&quot;
   * @return referenceNumber
   */
  @javax.annotation.Nonnull
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(@javax.annotation.Nonnull String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }


  public AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner display(@javax.annotation.Nullable String display) {
    this.display = display;
    return this;
  }

  /**
   * Display text for care context reference.Allows alpha numeric characters and special characters like \&quot;^[a-zA-Z0-9_\\\\-@,. \\\&quot;&#39;:|()/]{0,255}$\&quot;
   * @return display
   */
  @javax.annotation.Nullable
  public String getDisplay() {
    return display;
  }

  public void setDisplay(@javax.annotation.Nullable String display) {
    this.display = display;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner abdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner = (AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner) o;
    return Objects.equals(this.referenceNumber, abdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.referenceNumber) &&
        Objects.equals(this.display, abdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.display);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceNumber, display);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner {\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("referenceNumber");
    openapiFields.add("display");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("referenceNumber");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner is not found in the empty JSON string", AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("referenceNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `referenceNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referenceNumber").toString()));
      }
      if ((jsonObj.get("display") != null && !jsonObj.get("display").isJsonNull()) && !jsonObj.get("display").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `display` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner>() {
           @Override
           public void write(JsonWriter out, AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner
   * @throws IOException if the JSON string is invalid with respect to AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner
   */
  public static AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner.class);
  }

  /**
   * Convert an instance of AbdmUserInitiatedLinkingPhr3RequestPatientInnerCareContextsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

