/*
 * Ayushman Bharat Digital Mission - Consent Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model.phr;

import com.google.gson.*;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.*;

/**
 * ConsentManagement1RequestNotificationConsentDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-12T19:03:49.762814+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class ConsentManagement1RequestNotificationConsentDetail {
  public static final String SERIALIZED_NAME_SCHEMA_VERSION = "schemaVersion";
  @SerializedName(SERIALIZED_NAME_SCHEMA_VERSION)
  @javax.annotation.Nonnull
  private String schemaVersion;

  public static final String SERIALIZED_NAME_CONSENT_ID = "consentId";
  @SerializedName(SERIALIZED_NAME_CONSENT_ID)
  @javax.annotation.Nonnull
  private UUID consentId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_PATIENT = "patient";
  @SerializedName(SERIALIZED_NAME_PATIENT)
  @javax.annotation.Nonnull
  private ConsentManagement1RequestNotificationConsentDetailPatient patient;

  public static final String SERIALIZED_NAME_CARE_CONTEXTS = "careContexts";
  @SerializedName(SERIALIZED_NAME_CARE_CONTEXTS)
  @javax.annotation.Nonnull
  private List<ConsentManagement1RequestNotificationConsentDetailCareContextsInner> careContexts = new ArrayList<>();

  public static final String SERIALIZED_NAME_PURPOSE = "purpose";
  @SerializedName(SERIALIZED_NAME_PURPOSE)
  @javax.annotation.Nonnull
  private ConsentManagement1RequestNotificationConsentDetailPurpose purpose;

  public static final String SERIALIZED_NAME_HIP = "hip";
  @SerializedName(SERIALIZED_NAME_HIP)
  @javax.annotation.Nonnull
  private ConsentManagement1RequestNotificationConsentDetailHip hip;

  public static final String SERIALIZED_NAME_HIU = "hiu";
  @SerializedName(SERIALIZED_NAME_HIU)
  @javax.annotation.Nonnull
  private ConsentManagement1RequestNotificationConsentDetailHiu hiu;

  public static final String SERIALIZED_NAME_CONSENT_MANAGER = "consentManager";
  @SerializedName(SERIALIZED_NAME_CONSENT_MANAGER)
  @javax.annotation.Nonnull
  private ConsentManagement1RequestNotificationConsentDetailConsentManager consentManager;

  public static final String SERIALIZED_NAME_REQUESTER = "requester";
  @SerializedName(SERIALIZED_NAME_REQUESTER)
  @javax.annotation.Nonnull
  private ConsentManagement1RequestNotificationConsentDetailRequester requester;

  /**
   * Gets or Sets hiTypes
   */
  @JsonAdapter(HiTypesEnum.Adapter.class)
  public enum HiTypesEnum {
    PRESCRIPTION("Prescription"),
    
    DIAGNOSTIC_REPORT("DiagnosticReport"),
    
    OP_CONSULTATION("OPConsultation"),
    
    DISCHARGE_SUMMARY("DischargeSummary"),
    
    IMMUNIZATION_RECORD("ImmunizationRecord"),
    
    HEALTH_DOCUMENT_RECORD("HealthDocumentRecord"),
    
    WELLNESS_RECORD("WellnessRecord"),
    
    INVOICE("Invoice");

    private String value;

    HiTypesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static HiTypesEnum fromValue(String value) {
      for (HiTypesEnum b : HiTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<HiTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final HiTypesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public HiTypesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return HiTypesEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      HiTypesEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_HI_TYPES = "hiTypes";
  @SerializedName(SERIALIZED_NAME_HI_TYPES)
  @javax.annotation.Nonnull
  private List<HiTypesEnum> hiTypes = new ArrayList<>();

  public static final String SERIALIZED_NAME_PERMISSION = "permission";
  @SerializedName(SERIALIZED_NAME_PERMISSION)
  @javax.annotation.Nonnull
  private ConsentManagement1RequestNotificationConsentDetailPermission permission;

  public ConsentManagement1RequestNotificationConsentDetail() {
  }

  public ConsentManagement1RequestNotificationConsentDetail schemaVersion(@javax.annotation.Nonnull String schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

  /**
   * Get schemaVersion
   * @return schemaVersion
   */
  @javax.annotation.Nonnull
  public String getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(@javax.annotation.Nonnull String schemaVersion) {
    this.schemaVersion = schemaVersion;
  }


  public ConsentManagement1RequestNotificationConsentDetail consentId(@javax.annotation.Nonnull UUID consentId) {
    this.consentId = consentId;
    return this;
  }

  /**
   * Allows alpha numeric character and special characters like \&quot;^[0-9a-fA-F]{8}\\\\b-[0-9a-fA-F]{4}\\\\b-[0-9a-fA-F]{4}\\\\b-[0-9a-fA-F]{4}\\\\b-[0-9a-fA-F]{12}$\&quot;;
   * @return consentId
   */
  @javax.annotation.Nonnull
  public UUID getConsentId() {
    return consentId;
  }

  public void setConsentId(@javax.annotation.Nonnull UUID consentId) {
    this.consentId = consentId;
  }


  public ConsentManagement1RequestNotificationConsentDetail createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Allows alpha numeric character and special characters like \&quot;\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}.\\\\d{3}Z$\&quot;
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ConsentManagement1RequestNotificationConsentDetail patient(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailPatient patient) {
    this.patient = patient;
    return this;
  }

  /**
   * Get patient
   * @return patient
   */
  @javax.annotation.Nonnull
  public ConsentManagement1RequestNotificationConsentDetailPatient getPatient() {
    return patient;
  }

  public void setPatient(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailPatient patient) {
    this.patient = patient;
  }


  public ConsentManagement1RequestNotificationConsentDetail careContexts(@javax.annotation.Nonnull List<ConsentManagement1RequestNotificationConsentDetailCareContextsInner> careContexts) {
    this.careContexts = careContexts;
    return this;
  }

  public ConsentManagement1RequestNotificationConsentDetail addCareContextsItem(ConsentManagement1RequestNotificationConsentDetailCareContextsInner careContextsItem) {
    if (this.careContexts == null) {
      this.careContexts = new ArrayList<>();
    }
    this.careContexts.add(careContextsItem);
    return this;
  }

  /**
   * Get careContexts
   * @return careContexts
   */
  @javax.annotation.Nonnull
  public List<ConsentManagement1RequestNotificationConsentDetailCareContextsInner> getCareContexts() {
    return careContexts;
  }

  public void setCareContexts(@javax.annotation.Nonnull List<ConsentManagement1RequestNotificationConsentDetailCareContextsInner> careContexts) {
    this.careContexts = careContexts;
  }


  public ConsentManagement1RequestNotificationConsentDetail purpose(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailPurpose purpose) {
    this.purpose = purpose;
    return this;
  }

  /**
   * Get purpose
   * @return purpose
   */
  @javax.annotation.Nonnull
  public ConsentManagement1RequestNotificationConsentDetailPurpose getPurpose() {
    return purpose;
  }

  public void setPurpose(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailPurpose purpose) {
    this.purpose = purpose;
  }


  public ConsentManagement1RequestNotificationConsentDetail hip(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailHip hip) {
    this.hip = hip;
    return this;
  }

  /**
   * Get hip
   * @return hip
   */
  @javax.annotation.Nonnull
  public ConsentManagement1RequestNotificationConsentDetailHip getHip() {
    return hip;
  }

  public void setHip(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailHip hip) {
    this.hip = hip;
  }


  public ConsentManagement1RequestNotificationConsentDetail hiu(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailHiu hiu) {
    this.hiu = hiu;
    return this;
  }

  /**
   * Get hiu
   * @return hiu
   */
  @javax.annotation.Nonnull
  public ConsentManagement1RequestNotificationConsentDetailHiu getHiu() {
    return hiu;
  }

  public void setHiu(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailHiu hiu) {
    this.hiu = hiu;
  }


  public ConsentManagement1RequestNotificationConsentDetail consentManager(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailConsentManager consentManager) {
    this.consentManager = consentManager;
    return this;
  }

  /**
   * Get consentManager
   * @return consentManager
   */
  @javax.annotation.Nonnull
  public ConsentManagement1RequestNotificationConsentDetailConsentManager getConsentManager() {
    return consentManager;
  }

  public void setConsentManager(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailConsentManager consentManager) {
    this.consentManager = consentManager;
  }


  public ConsentManagement1RequestNotificationConsentDetail requester(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailRequester requester) {
    this.requester = requester;
    return this;
  }

  /**
   * Get requester
   * @return requester
   */
  @javax.annotation.Nonnull
  public ConsentManagement1RequestNotificationConsentDetailRequester getRequester() {
    return requester;
  }

  public void setRequester(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailRequester requester) {
    this.requester = requester;
  }


  public ConsentManagement1RequestNotificationConsentDetail hiTypes(@javax.annotation.Nonnull List<HiTypesEnum> hiTypes) {
    this.hiTypes = hiTypes;
    return this;
  }

  public ConsentManagement1RequestNotificationConsentDetail addHiTypesItem(HiTypesEnum hiTypesItem) {
    if (this.hiTypes == null) {
      this.hiTypes = new ArrayList<>();
    }
    this.hiTypes.add(hiTypesItem);
    return this;
  }

  /**
   * Get hiTypes
   * @return hiTypes
   */
  @javax.annotation.Nonnull
  public List<HiTypesEnum> getHiTypes() {
    return hiTypes;
  }

  public void setHiTypes(@javax.annotation.Nonnull List<HiTypesEnum> hiTypes) {
    this.hiTypes = hiTypes;
  }


  public ConsentManagement1RequestNotificationConsentDetail permission(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailPermission permission) {
    this.permission = permission;
    return this;
  }

  /**
   * Get permission
   * @return permission
   */
  @javax.annotation.Nonnull
  public ConsentManagement1RequestNotificationConsentDetailPermission getPermission() {
    return permission;
  }

  public void setPermission(@javax.annotation.Nonnull ConsentManagement1RequestNotificationConsentDetailPermission permission) {
    this.permission = permission;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentManagement1RequestNotificationConsentDetail consentManagement1RequestNotificationConsentDetail = (ConsentManagement1RequestNotificationConsentDetail) o;
    return Objects.equals(this.schemaVersion, consentManagement1RequestNotificationConsentDetail.schemaVersion) &&
        Objects.equals(this.consentId, consentManagement1RequestNotificationConsentDetail.consentId) &&
        Objects.equals(this.createdAt, consentManagement1RequestNotificationConsentDetail.createdAt) &&
        Objects.equals(this.patient, consentManagement1RequestNotificationConsentDetail.patient) &&
        Objects.equals(this.careContexts, consentManagement1RequestNotificationConsentDetail.careContexts) &&
        Objects.equals(this.purpose, consentManagement1RequestNotificationConsentDetail.purpose) &&
        Objects.equals(this.hip, consentManagement1RequestNotificationConsentDetail.hip) &&
        Objects.equals(this.hiu, consentManagement1RequestNotificationConsentDetail.hiu) &&
        Objects.equals(this.consentManager, consentManagement1RequestNotificationConsentDetail.consentManager) &&
        Objects.equals(this.requester, consentManagement1RequestNotificationConsentDetail.requester) &&
        Objects.equals(this.hiTypes, consentManagement1RequestNotificationConsentDetail.hiTypes) &&
        Objects.equals(this.permission, consentManagement1RequestNotificationConsentDetail.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, consentId, createdAt, patient, careContexts, purpose, hip, hiu, consentManager, requester, hiTypes, permission);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentManagement1RequestNotificationConsentDetail {\n");
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    consentId: ").append(toIndentedString(consentId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    patient: ").append(toIndentedString(patient)).append("\n");
    sb.append("    careContexts: ").append(toIndentedString(careContexts)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    hip: ").append(toIndentedString(hip)).append("\n");
    sb.append("    hiu: ").append(toIndentedString(hiu)).append("\n");
    sb.append("    consentManager: ").append(toIndentedString(consentManager)).append("\n");
    sb.append("    requester: ").append(toIndentedString(requester)).append("\n");
    sb.append("    hiTypes: ").append(toIndentedString(hiTypes)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("schemaVersion");
    openapiFields.add("consentId");
    openapiFields.add("createdAt");
    openapiFields.add("patient");
    openapiFields.add("careContexts");
    openapiFields.add("purpose");
    openapiFields.add("hip");
    openapiFields.add("hiu");
    openapiFields.add("consentManager");
    openapiFields.add("requester");
    openapiFields.add("hiTypes");
    openapiFields.add("permission");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("schemaVersion");
    openapiRequiredFields.add("consentId");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("patient");
    openapiRequiredFields.add("careContexts");
    openapiRequiredFields.add("purpose");
    openapiRequiredFields.add("hip");
    openapiRequiredFields.add("hiu");
    openapiRequiredFields.add("consentManager");
    openapiRequiredFields.add("requester");
    openapiRequiredFields.add("hiTypes");
    openapiRequiredFields.add("permission");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConsentManagement1RequestNotificationConsentDetail
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConsentManagement1RequestNotificationConsentDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConsentManagement1RequestNotificationConsentDetail is not found in the empty JSON string", ConsentManagement1RequestNotificationConsentDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConsentManagement1RequestNotificationConsentDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConsentManagement1RequestNotificationConsentDetail` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConsentManagement1RequestNotificationConsentDetail.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("schemaVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `schemaVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("schemaVersion").toString()));
      }
      if (!jsonObj.get("consentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `consentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("consentId").toString()));
      }
      // validate the required field `patient`
      ConsentManagement1RequestNotificationConsentDetailPatient.validateJsonElement(jsonObj.get("patient"));
      // ensure the json data is an array
      if (!jsonObj.get("careContexts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `careContexts` to be an array in the JSON string but got `%s`", jsonObj.get("careContexts").toString()));
      }

      JsonArray jsonArraycareContexts = jsonObj.getAsJsonArray("careContexts");
      // validate the required field `careContexts` (array)
      for (int i = 0; i < jsonArraycareContexts.size(); i++) {
        ConsentManagement1RequestNotificationConsentDetailCareContextsInner.validateJsonElement(jsonArraycareContexts.get(i));
      };
      // validate the required field `purpose`
      ConsentManagement1RequestNotificationConsentDetailPurpose.validateJsonElement(jsonObj.get("purpose"));
      // validate the required field `hip`
      ConsentManagement1RequestNotificationConsentDetailHip.validateJsonElement(jsonObj.get("hip"));
      // validate the required field `hiu`
      ConsentManagement1RequestNotificationConsentDetailHiu.validateJsonElement(jsonObj.get("hiu"));
      // validate the required field `consentManager`
      ConsentManagement1RequestNotificationConsentDetailConsentManager.validateJsonElement(jsonObj.get("consentManager"));
      // validate the required field `requester`
      ConsentManagement1RequestNotificationConsentDetailRequester.validateJsonElement(jsonObj.get("requester"));
      // ensure the required json array is present
      if (jsonObj.get("hiTypes") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("hiTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `hiTypes` to be an array in the JSON string but got `%s`", jsonObj.get("hiTypes").toString()));
      }
      // validate the required field `permission`
      ConsentManagement1RequestNotificationConsentDetailPermission.validateJsonElement(jsonObj.get("permission"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsentManagement1RequestNotificationConsentDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsentManagement1RequestNotificationConsentDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsentManagement1RequestNotificationConsentDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsentManagement1RequestNotificationConsentDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsentManagement1RequestNotificationConsentDetail>() {
           @Override
           public void write(JsonWriter out, ConsentManagement1RequestNotificationConsentDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsentManagement1RequestNotificationConsentDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConsentManagement1RequestNotificationConsentDetail given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConsentManagement1RequestNotificationConsentDetail
   * @throws IOException if the JSON string is invalid with respect to ConsentManagement1RequestNotificationConsentDetail
   */
  public static ConsentManagement1RequestNotificationConsentDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsentManagement1RequestNotificationConsentDetail.class);
  }

  /**
   * Convert an instance of ConsentManagement1RequestNotificationConsentDetail to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

