/*
 * Ayushman Bharat Digital Mission - Consent Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model.phr;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * In the request body, either ‘consentRequest’ or ‘error’ must be included.&lt;br&gt; &lt;ol type&#x3D;&#39;a&#39;&gt;&lt;br/&gt; &lt;li&gt;Incase of success scenario,consentRequest is mandatory and error is optional &lt;/li&gt; &lt;li&gt;Incase of failure scenario,error is mandatory and consentRequest is optional&lt;/li&gt; &lt;li&gt;response is mandatory object in both the cases&lt;/li&gt; &lt;/ol&gt;
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-12T19:03:49.762814+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class ConsentManagement4Request {
  public static final String SERIALIZED_NAME_CONSENT_REQUEST = "consentRequest";
  @SerializedName(SERIALIZED_NAME_CONSENT_REQUEST)
  @javax.annotation.Nonnull
  private ConsentManagement4RequestConsentRequest consentRequest;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private AbdmConsentManagement2RequestError error;

  public static final String SERIALIZED_NAME_RESPONSE = "response";
  @SerializedName(SERIALIZED_NAME_RESPONSE)
  @javax.annotation.Nonnull
  private ConsentManagement4RequestResponse response;

  public static final String SERIALIZED_NAME_RESP = "resp";
  @SerializedName(SERIALIZED_NAME_RESP)
  @javax.annotation.Nonnull
  private String resp;

  public ConsentManagement4Request() {
  }

  public ConsentManagement4Request consentRequest(@javax.annotation.Nonnull ConsentManagement4RequestConsentRequest consentRequest) {
    this.consentRequest = consentRequest;
    return this;
  }

  /**
   * Get consentRequest
   * @return consentRequest
   */
  @javax.annotation.Nonnull
  public ConsentManagement4RequestConsentRequest getConsentRequest() {
    return consentRequest;
  }

  public void setConsentRequest(@javax.annotation.Nonnull ConsentManagement4RequestConsentRequest consentRequest) {
    this.consentRequest = consentRequest;
  }


  public ConsentManagement4Request error(@javax.annotation.Nullable AbdmConsentManagement2RequestError error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  public AbdmConsentManagement2RequestError getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable AbdmConsentManagement2RequestError error) {
    this.error = error;
  }


  public ConsentManagement4Request response(@javax.annotation.Nonnull ConsentManagement4RequestResponse response) {
    this.response = response;
    return this;
  }

  /**
   * Get response
   * @return response
   */
  @javax.annotation.Nonnull
  public ConsentManagement4RequestResponse getResponse() {
    return response;
  }

  public void setResponse(@javax.annotation.Nonnull ConsentManagement4RequestResponse response) {
    this.response = response;
  }


  public ConsentManagement4Request resp(@javax.annotation.Nonnull String resp) {
    this.resp = resp;
    return this;
  }

  /**
   * Get resp
   * @return resp
   */
  @javax.annotation.Nonnull
  public String getResp() {
    return resp;
  }

  public void setResp(@javax.annotation.Nonnull String resp) {
    this.resp = resp;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentManagement4Request consentManagement4Request = (ConsentManagement4Request) o;
    return Objects.equals(this.consentRequest, consentManagement4Request.consentRequest) &&
        Objects.equals(this.error, consentManagement4Request.error) &&
        Objects.equals(this.response, consentManagement4Request.response) &&
        Objects.equals(this.resp, consentManagement4Request.resp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consentRequest, error, response, resp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentManagement4Request {\n");
    sb.append("    consentRequest: ").append(toIndentedString(consentRequest)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    resp: ").append(toIndentedString(resp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("consentRequest");
    openapiFields.add("error");
    openapiFields.add("response");
    openapiFields.add("resp");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("consentRequest");
    openapiRequiredFields.add("error");
    openapiRequiredFields.add("response");
    openapiRequiredFields.add("resp");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConsentManagement4Request
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConsentManagement4Request.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConsentManagement4Request is not found in the empty JSON string", ConsentManagement4Request.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConsentManagement4Request.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConsentManagement4Request` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConsentManagement4Request.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `consentRequest`
      ConsentManagement4RequestConsentRequest.validateJsonElement(jsonObj.get("consentRequest"));
      // validate the required field `error`
      AbdmConsentManagement2RequestError.validateJsonElement(jsonObj.get("error"));
      // validate the required field `response`
      ConsentManagement4RequestResponse.validateJsonElement(jsonObj.get("response"));
      if (!jsonObj.get("resp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resp").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsentManagement4Request.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsentManagement4Request' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsentManagement4Request> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsentManagement4Request.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsentManagement4Request>() {
           @Override
           public void write(JsonWriter out, ConsentManagement4Request value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsentManagement4Request read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConsentManagement4Request given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConsentManagement4Request
   * @throws IOException if the JSON string is invalid with respect to ConsentManagement4Request
   */
  public static ConsentManagement4Request fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsentManagement4Request.class);
  }

  /**
   * Convert an instance of ConsentManagement4Request to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

