/*
 * PHR V3 Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model.phr;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * LoginOtpVerifyMobile200ResponseUsersInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-10T18:02:09.764020+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class LoginOtpVerifyMobile200ResponseUsersInner {
  public static final String SERIALIZED_NAME_ABHA_ADDRESS = "abhaAddress";
  @SerializedName(SERIALIZED_NAME_ABHA_ADDRESS)
  @javax.annotation.Nullable
  private String abhaAddress;

  public static final String SERIALIZED_NAME_ABHA_NUMBER = "abhaNumber";
  @SerializedName(SERIALIZED_NAME_ABHA_NUMBER)
  @javax.annotation.Nullable
  private String abhaNumber;

  public static final String SERIALIZED_NAME_FULL_NAME = "fullName";
  @SerializedName(SERIALIZED_NAME_FULL_NAME)
  @javax.annotation.Nullable
  private String fullName;

  public static final String SERIALIZED_NAME_KYC_STATUS = "kycStatus";
  @SerializedName(SERIALIZED_NAME_KYC_STATUS)
  @javax.annotation.Nullable
  private String kycStatus;

  public static final String SERIALIZED_NAME_PROFILE_PHOTO = "profilePhoto";
  @SerializedName(SERIALIZED_NAME_PROFILE_PHOTO)
  @javax.annotation.Nullable
  private String profilePhoto;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  @javax.annotation.Nullable
  private String gender;

  public static final String SERIALIZED_NAME_AGE = "age";
  @SerializedName(SERIALIZED_NAME_AGE)
  @javax.annotation.Nullable
  private Integer age;

  public LoginOtpVerifyMobile200ResponseUsersInner() {
  }

  public LoginOtpVerifyMobile200ResponseUsersInner abhaAddress(@javax.annotation.Nullable String abhaAddress) {
    this.abhaAddress = abhaAddress;
    return this;
  }

  /**
   * Get abhaAddress
   * @return abhaAddress
   */
  @javax.annotation.Nullable
  public String getAbhaAddress() {
    return abhaAddress;
  }

  public void setAbhaAddress(@javax.annotation.Nullable String abhaAddress) {
    this.abhaAddress = abhaAddress;
  }


  public LoginOtpVerifyMobile200ResponseUsersInner abhaNumber(@javax.annotation.Nullable String abhaNumber) {
    this.abhaNumber = abhaNumber;
    return this;
  }

  /**
   * Get abhaNumber
   * @return abhaNumber
   */
  @javax.annotation.Nullable
  public String getAbhaNumber() {
    return abhaNumber;
  }

  public void setAbhaNumber(@javax.annotation.Nullable String abhaNumber) {
    this.abhaNumber = abhaNumber;
  }


  public LoginOtpVerifyMobile200ResponseUsersInner fullName(@javax.annotation.Nullable String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * Get fullName
   * @return fullName
   */
  @javax.annotation.Nullable
  public String getFullName() {
    return fullName;
  }

  public void setFullName(@javax.annotation.Nullable String fullName) {
    this.fullName = fullName;
  }


  public LoginOtpVerifyMobile200ResponseUsersInner kycStatus(@javax.annotation.Nullable String kycStatus) {
    this.kycStatus = kycStatus;
    return this;
  }

  /**
   * Get kycStatus
   * @return kycStatus
   */
  @javax.annotation.Nullable
  public String getKycStatus() {
    return kycStatus;
  }

  public void setKycStatus(@javax.annotation.Nullable String kycStatus) {
    this.kycStatus = kycStatus;
  }


  public LoginOtpVerifyMobile200ResponseUsersInner profilePhoto(@javax.annotation.Nullable String profilePhoto) {
    this.profilePhoto = profilePhoto;
    return this;
  }

  /**
   * Get profilePhoto
   * @return profilePhoto
   */
  @javax.annotation.Nullable
  public String getProfilePhoto() {
    return profilePhoto;
  }

  public void setProfilePhoto(@javax.annotation.Nullable String profilePhoto) {
    this.profilePhoto = profilePhoto;
  }


  public LoginOtpVerifyMobile200ResponseUsersInner status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }

  public LoginOtpVerifyMobile200ResponseUsersInner gender(@javax.annotation.Nullable String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * Get gender
   * @return gender
   */
  @javax.annotation.Nullable
  public String getGender() {
    return gender;
  }

  public void setGender(@javax.annotation.Nullable String gender) {
    this.gender = gender;
  }

  public LoginOtpVerifyMobile200ResponseUsersInner age(@javax.annotation.Nullable Integer age) {
    this.age = age;
    return this;
  }

  /**
   * Get age
   * @return age
   */
  @javax.annotation.Nullable
  public Integer getAge() {
    return age;
  }

  public void setAge(@javax.annotation.Nullable Integer age) {
    this.age = age;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginOtpVerifyMobile200ResponseUsersInner loginOtpVerifyMobile200ResponseUsersInner = (LoginOtpVerifyMobile200ResponseUsersInner) o;
    return Objects.equals(this.abhaAddress, loginOtpVerifyMobile200ResponseUsersInner.abhaAddress) &&
        Objects.equals(this.abhaNumber, loginOtpVerifyMobile200ResponseUsersInner.abhaNumber) &&
        Objects.equals(this.fullName, loginOtpVerifyMobile200ResponseUsersInner.fullName) &&
        Objects.equals(this.kycStatus, loginOtpVerifyMobile200ResponseUsersInner.kycStatus) &&
        Objects.equals(this.profilePhoto, loginOtpVerifyMobile200ResponseUsersInner.profilePhoto) &&
        Objects.equals(this.status, loginOtpVerifyMobile200ResponseUsersInner.status) &&
        Objects.equals(this.gender, loginOtpVerifyMobile200ResponseUsersInner.gender) &&
        Objects.equals(this.age, loginOtpVerifyMobile200ResponseUsersInner.age);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abhaAddress, abhaNumber, fullName, kycStatus, profilePhoto, status, gender, age);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginOtpVerifyMobile200ResponseUsersInner {\n");
    sb.append("    abhaAddress: ").append(toIndentedString(abhaAddress)).append("\n");
    sb.append("    abhaNumber: ").append(toIndentedString(abhaNumber)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    kycStatus: ").append(toIndentedString(kycStatus)).append("\n");
    sb.append("    profilePhoto: ").append(toIndentedString(profilePhoto)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("abhaAddress");
    openapiFields.add("abhaNumber");
    openapiFields.add("fullName");
    openapiFields.add("kycStatus");
    openapiFields.add("profilePhoto");
    openapiFields.add("status");
    openapiFields.add("gender");
    openapiFields.add("age");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LoginOtpVerifyMobile200ResponseUsersInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LoginOtpVerifyMobile200ResponseUsersInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LoginOtpVerifyMobile200ResponseUsersInner is not found in the empty JSON string", LoginOtpVerifyMobile200ResponseUsersInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LoginOtpVerifyMobile200ResponseUsersInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LoginOtpVerifyMobile200ResponseUsersInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("abhaAddress") != null && !jsonObj.get("abhaAddress").isJsonNull()) && !jsonObj.get("abhaAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `abhaAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("abhaAddress").toString()));
      }
      if ((jsonObj.get("abhaNumber") != null && !jsonObj.get("abhaNumber").isJsonNull()) && !jsonObj.get("abhaNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `abhaNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("abhaNumber").toString()));
      }
      if ((jsonObj.get("fullName") != null && !jsonObj.get("fullName").isJsonNull()) && !jsonObj.get("fullName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fullName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fullName").toString()));
      }
      if ((jsonObj.get("kycStatus") != null && !jsonObj.get("kycStatus").isJsonNull()) && !jsonObj.get("kycStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kycStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kycStatus").toString()));
      }
      if ((jsonObj.get("profilePhoto") != null && !jsonObj.get("profilePhoto").isJsonNull()) && !jsonObj.get("profilePhoto").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `profilePhoto` to be a primitive type in the JSON string but got `%s`", jsonObj.get("profilePhoto").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoginOtpVerifyMobile200ResponseUsersInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoginOtpVerifyMobile200ResponseUsersInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoginOtpVerifyMobile200ResponseUsersInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoginOtpVerifyMobile200ResponseUsersInner.class));

       return (TypeAdapter<T>) new TypeAdapter<LoginOtpVerifyMobile200ResponseUsersInner>() {
           @Override
           public void write(JsonWriter out, LoginOtpVerifyMobile200ResponseUsersInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LoginOtpVerifyMobile200ResponseUsersInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LoginOtpVerifyMobile200ResponseUsersInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LoginOtpVerifyMobile200ResponseUsersInner
   * @throws IOException if the JSON string is invalid with respect to LoginOtpVerifyMobile200ResponseUsersInner
   */
  public static LoginOtpVerifyMobile200ResponseUsersInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoginOtpVerifyMobile200ResponseUsersInner.class);
  }

  /**
   * Convert an instance of LoginOtpVerifyMobile200ResponseUsersInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

