/*
 * Health Facility Registry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;
import in.docq.abha.rest.client.model.MultipleHRPRequest;

import java.io.IOException;
import java.util.*;

/**
 * BridgeAddUpdateRequestDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-04T14:58:27.910059+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class BridgeAddUpdateRequestDTO {
  public static final String SERIALIZED_NAME_FACILITY_ID = "facilityId";
  @SerializedName(SERIALIZED_NAME_FACILITY_ID)
  @javax.annotation.Nonnull
  private String facilityId;

  public static final String SERIALIZED_NAME_FACILITY_NAME = "facilityName";
  @SerializedName(SERIALIZED_NAME_FACILITY_NAME)
  @javax.annotation.Nonnull
  private String facilityName;

  public static final String SERIALIZED_NAME_H_R_P = "HRP";
  @SerializedName(SERIALIZED_NAME_H_R_P)
  @javax.annotation.Nullable
  private List<in.docq.abha.rest.client.model.MultipleHRPRequest> HRP = new ArrayList<>();

  public BridgeAddUpdateRequestDTO() {
  }

  public BridgeAddUpdateRequestDTO facilityId(@javax.annotation.Nonnull String facilityId) {
    this.facilityId = facilityId;
    return this;
  }

  /**
   * Get facilityId
   * @return facilityId
   */
  @javax.annotation.Nonnull
  public String getFacilityId() {
    return facilityId;
  }

  public void setFacilityId(@javax.annotation.Nonnull String facilityId) {
    this.facilityId = facilityId;
  }


  public BridgeAddUpdateRequestDTO facilityName(@javax.annotation.Nonnull String facilityName) {
    this.facilityName = facilityName;
    return this;
  }

  /**
   * Get facilityName
   * @return facilityName
   */
  @javax.annotation.Nonnull
  public String getFacilityName() {
    return facilityName;
  }

  public void setFacilityName(@javax.annotation.Nonnull String facilityName) {
    this.facilityName = facilityName;
  }


  public BridgeAddUpdateRequestDTO HRP(@javax.annotation.Nullable List<in.docq.abha.rest.client.model.MultipleHRPRequest> HRP) {
    this.HRP = HRP;
    return this;
  }

  public BridgeAddUpdateRequestDTO addHRPItem(in.docq.abha.rest.client.model.MultipleHRPRequest HRPItem) {
    if (this.HRP == null) {
      this.HRP = new ArrayList<>();
    }
    this.HRP.add(HRPItem);
    return this;
  }

  /**
   * Get HRP
   * @return HRP
   */
  @javax.annotation.Nullable
  public List<in.docq.abha.rest.client.model.MultipleHRPRequest> getHRP() {
    return HRP;
  }

  public void setHRP(@javax.annotation.Nullable List<in.docq.abha.rest.client.model.MultipleHRPRequest> HRP) {
    this.HRP = HRP;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BridgeAddUpdateRequestDTO bridgeAddUpdateRequestDTO = (BridgeAddUpdateRequestDTO) o;
    return Objects.equals(this.facilityId, bridgeAddUpdateRequestDTO.facilityId) &&
        Objects.equals(this.facilityName, bridgeAddUpdateRequestDTO.facilityName) &&
        Objects.equals(this.HRP, bridgeAddUpdateRequestDTO.HRP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(facilityId, facilityName, HRP);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BridgeAddUpdateRequestDTO {\n");
    sb.append("    facilityId: ").append(toIndentedString(facilityId)).append("\n");
    sb.append("    facilityName: ").append(toIndentedString(facilityName)).append("\n");
    sb.append("    HRP: ").append(toIndentedString(HRP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("facilityId");
    openapiFields.add("facilityName");
    openapiFields.add("HRP");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("facilityId");
    openapiRequiredFields.add("facilityName");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BridgeAddUpdateRequestDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BridgeAddUpdateRequestDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BridgeAddUpdateRequestDTO is not found in the empty JSON string", BridgeAddUpdateRequestDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BridgeAddUpdateRequestDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BridgeAddUpdateRequestDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BridgeAddUpdateRequestDTO.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("facilityId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `facilityId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("facilityId").toString()));
      }
      if (!jsonObj.get("facilityName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `facilityName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("facilityName").toString()));
      }
      if (jsonObj.get("HRP") != null && !jsonObj.get("HRP").isJsonNull()) {
        JsonArray jsonArrayHRP = jsonObj.getAsJsonArray("HRP");
        if (jsonArrayHRP != null) {
          // ensure the json data is an array
          if (!jsonObj.get("HRP").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `HRP` to be an array in the JSON string but got `%s`", jsonObj.get("HRP").toString()));
          }

          // validate the optional field `HRP` (array)
          for (int i = 0; i < jsonArrayHRP.size(); i++) {
            MultipleHRPRequest.validateJsonElement(jsonArrayHRP.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BridgeAddUpdateRequestDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BridgeAddUpdateRequestDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BridgeAddUpdateRequestDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BridgeAddUpdateRequestDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<BridgeAddUpdateRequestDTO>() {
           @Override
           public void write(JsonWriter out, BridgeAddUpdateRequestDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BridgeAddUpdateRequestDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BridgeAddUpdateRequestDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BridgeAddUpdateRequestDTO
   * @throws IOException if the JSON string is invalid with respect to BridgeAddUpdateRequestDTO
   */
  public static BridgeAddUpdateRequestDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BridgeAddUpdateRequestDTO.class);
  }

  /**
   * Convert an instance of BridgeAddUpdateRequestDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

