/*
 * Ayushman Bharat Digital Mission - Consent Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * ConsentManagement6Request1ConsentConsentDetailCareContextsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-12T19:03:49.762814+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class ConsentManagement6Request1ConsentConsentDetailCareContextsInner {
  public static final String SERIALIZED_NAME_PATIENT_REFERENCE = "patientReference";
  @SerializedName(SERIALIZED_NAME_PATIENT_REFERENCE)
  @javax.annotation.Nonnull
  private String patientReference;

  public static final String SERIALIZED_NAME_CARE_CONTEXT_REFERENCE = "careContextReference";
  @SerializedName(SERIALIZED_NAME_CARE_CONTEXT_REFERENCE)
  @javax.annotation.Nonnull
  private String careContextReference;

  public ConsentManagement6Request1ConsentConsentDetailCareContextsInner() {
  }

  public ConsentManagement6Request1ConsentConsentDetailCareContextsInner patientReference(@javax.annotation.Nonnull String patientReference) {
    this.patientReference = patientReference;
    return this;
  }

  /**
   * A patient identifier with which patient is registered in the facility/hospital. Allows alpha numeric character and special characters like ^[a-zA-Z0-9_\\-@,. \&quot;&#39;:|()/]{0,255}$
   * @return patientReference
   */
  @javax.annotation.Nonnull
  public String getPatientReference() {
    return patientReference;
  }

  public void setPatientReference(@javax.annotation.Nonnull String patientReference) {
    this.patientReference = patientReference;
  }


  public ConsentManagement6Request1ConsentConsentDetailCareContextsInner careContextReference(@javax.annotation.Nonnull String careContextReference) {
    this.careContextReference = careContextReference;
    return this;
  }

  /**
   * An identifier of patient&#39;s care context created in HIP. A care context is a group of patient&#39;s health data (Not the actual health data). Allows alpha numeric character and special characters like ^[a-zA-Z0-9_\\-@,. \&quot;&#39;:|()/]{0,255}$
   * @return careContextReference
   */
  @javax.annotation.Nonnull
  public String getCareContextReference() {
    return careContextReference;
  }

  public void setCareContextReference(@javax.annotation.Nonnull String careContextReference) {
    this.careContextReference = careContextReference;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentManagement6Request1ConsentConsentDetailCareContextsInner consentManagement6Request1ConsentConsentDetailCareContextsInner = (ConsentManagement6Request1ConsentConsentDetailCareContextsInner) o;
    return Objects.equals(this.patientReference, consentManagement6Request1ConsentConsentDetailCareContextsInner.patientReference) &&
        Objects.equals(this.careContextReference, consentManagement6Request1ConsentConsentDetailCareContextsInner.careContextReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(patientReference, careContextReference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentManagement6Request1ConsentConsentDetailCareContextsInner {\n");
    sb.append("    patientReference: ").append(toIndentedString(patientReference)).append("\n");
    sb.append("    careContextReference: ").append(toIndentedString(careContextReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("patientReference");
    openapiFields.add("careContextReference");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("patientReference");
    openapiRequiredFields.add("careContextReference");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConsentManagement6Request1ConsentConsentDetailCareContextsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConsentManagement6Request1ConsentConsentDetailCareContextsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConsentManagement6Request1ConsentConsentDetailCareContextsInner is not found in the empty JSON string", ConsentManagement6Request1ConsentConsentDetailCareContextsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConsentManagement6Request1ConsentConsentDetailCareContextsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConsentManagement6Request1ConsentConsentDetailCareContextsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConsentManagement6Request1ConsentConsentDetailCareContextsInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("patientReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `patientReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("patientReference").toString()));
      }
      if (!jsonObj.get("careContextReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `careContextReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("careContextReference").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsentManagement6Request1ConsentConsentDetailCareContextsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsentManagement6Request1ConsentConsentDetailCareContextsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsentManagement6Request1ConsentConsentDetailCareContextsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsentManagement6Request1ConsentConsentDetailCareContextsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsentManagement6Request1ConsentConsentDetailCareContextsInner>() {
           @Override
           public void write(JsonWriter out, ConsentManagement6Request1ConsentConsentDetailCareContextsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsentManagement6Request1ConsentConsentDetailCareContextsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConsentManagement6Request1ConsentConsentDetailCareContextsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConsentManagement6Request1ConsentConsentDetailCareContextsInner
   * @throws IOException if the JSON string is invalid with respect to ConsentManagement6Request1ConsentConsentDetailCareContextsInner
   */
  public static ConsentManagement6Request1ConsentConsentDetailCareContextsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsentManagement6Request1ConsentConsentDetailCareContextsInner.class);
  }

  /**
   * Convert an instance of ConsentManagement6Request1ConsentConsentDetailCareContextsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

