/*
 * Ayushman Bharat Digital Mission - Consent Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * ConsentManagement6Request1ConsentConsentDetailRequester
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-12T19:03:49.762814+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class ConsentManagement6Request1ConsentConsentDetailRequester {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  @javax.annotation.Nonnull
  private ConsentManagement6Request1ConsentConsentDetailRequesterIdentifier identifier;

  public ConsentManagement6Request1ConsentConsentDetailRequester() {
  }

  public ConsentManagement6Request1ConsentConsentDetailRequester name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the requester
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public ConsentManagement6Request1ConsentConsentDetailRequester identifier(@javax.annotation.Nonnull ConsentManagement6Request1ConsentConsentDetailRequesterIdentifier identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   */
  @javax.annotation.Nonnull
  public ConsentManagement6Request1ConsentConsentDetailRequesterIdentifier getIdentifier() {
    return identifier;
  }

  public void setIdentifier(@javax.annotation.Nonnull ConsentManagement6Request1ConsentConsentDetailRequesterIdentifier identifier) {
    this.identifier = identifier;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentManagement6Request1ConsentConsentDetailRequester consentManagement6Request1ConsentConsentDetailRequester = (ConsentManagement6Request1ConsentConsentDetailRequester) o;
    return Objects.equals(this.name, consentManagement6Request1ConsentConsentDetailRequester.name) &&
        Objects.equals(this.identifier, consentManagement6Request1ConsentConsentDetailRequester.identifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, identifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentManagement6Request1ConsentConsentDetailRequester {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("identifier");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("identifier");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConsentManagement6Request1ConsentConsentDetailRequester
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConsentManagement6Request1ConsentConsentDetailRequester.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConsentManagement6Request1ConsentConsentDetailRequester is not found in the empty JSON string", ConsentManagement6Request1ConsentConsentDetailRequester.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConsentManagement6Request1ConsentConsentDetailRequester.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConsentManagement6Request1ConsentConsentDetailRequester` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConsentManagement6Request1ConsentConsentDetailRequester.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the required field `identifier`
      ConsentManagement6Request1ConsentConsentDetailRequesterIdentifier.validateJsonElement(jsonObj.get("identifier"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsentManagement6Request1ConsentConsentDetailRequester.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsentManagement6Request1ConsentConsentDetailRequester' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsentManagement6Request1ConsentConsentDetailRequester> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsentManagement6Request1ConsentConsentDetailRequester.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsentManagement6Request1ConsentConsentDetailRequester>() {
           @Override
           public void write(JsonWriter out, ConsentManagement6Request1ConsentConsentDetailRequester value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsentManagement6Request1ConsentConsentDetailRequester read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConsentManagement6Request1ConsentConsentDetailRequester given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConsentManagement6Request1ConsentConsentDetailRequester
   * @throws IOException if the JSON string is invalid with respect to ConsentManagement6Request1ConsentConsentDetailRequester
   */
  public static ConsentManagement6Request1ConsentConsentDetailRequester fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsentManagement6Request1ConsentConsentDetailRequester.class);
  }

  /**
   * Convert an instance of ConsentManagement6Request1ConsentConsentDetailRequester to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

