/*
 * HFR APIs
 * The following are APIs hosted by HFR for public use.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * FacilitySpecialities
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-25T14:50:59.077868+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class FacilitySpecialities {
  public static final String SERIALIZED_NAME_SYSTEM_OF_MEDICINE_CODE = "systemOfMedicineCode";
  @SerializedName(SERIALIZED_NAME_SYSTEM_OF_MEDICINE_CODE)
  @javax.annotation.Nullable
  private String systemOfMedicineCode;

  public static final String SERIALIZED_NAME_IS_SPECIALIZATION_AVALAIBLE = "isSpecializationAvalaible";
  @SerializedName(SERIALIZED_NAME_IS_SPECIALIZATION_AVALAIBLE)
  @javax.annotation.Nullable
  private String isSpecializationAvalaible;

  public static final String SERIALIZED_NAME_SPECIALITIES = "specialities";
  @SerializedName(SERIALIZED_NAME_SPECIALITIES)
  @javax.annotation.Nullable
  private List<String> specialities = new ArrayList<>();

  public FacilitySpecialities() {
  }

  public FacilitySpecialities systemOfMedicineCode(@javax.annotation.Nullable String systemOfMedicineCode) {
    this.systemOfMedicineCode = systemOfMedicineCode;
    return this;
  }

  /**
   * Get systemOfMedicineCode
   * @return systemOfMedicineCode
   */
  @javax.annotation.Nullable
  public String getSystemOfMedicineCode() {
    return systemOfMedicineCode;
  }

  public void setSystemOfMedicineCode(@javax.annotation.Nullable String systemOfMedicineCode) {
    this.systemOfMedicineCode = systemOfMedicineCode;
  }


  public FacilitySpecialities isSpecializationAvalaible(@javax.annotation.Nullable String isSpecializationAvalaible) {
    this.isSpecializationAvalaible = isSpecializationAvalaible;
    return this;
  }

  /**
   * Get isSpecializationAvalaible
   * @return isSpecializationAvalaible
   */
  @javax.annotation.Nullable
  public String getIsSpecializationAvalaible() {
    return isSpecializationAvalaible;
  }

  public void setIsSpecializationAvalaible(@javax.annotation.Nullable String isSpecializationAvalaible) {
    this.isSpecializationAvalaible = isSpecializationAvalaible;
  }


  public FacilitySpecialities specialities(@javax.annotation.Nullable List<String> specialities) {
    this.specialities = specialities;
    return this;
  }

  public FacilitySpecialities addSpecialitiesItem(String specialitiesItem) {
    if (this.specialities == null) {
      this.specialities = new ArrayList<>();
    }
    this.specialities.add(specialitiesItem);
    return this;
  }

  /**
   * Get specialities
   * @return specialities
   */
  @javax.annotation.Nullable
  public List<String> getSpecialities() {
    return specialities;
  }

  public void setSpecialities(@javax.annotation.Nullable List<String> specialities) {
    this.specialities = specialities;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacilitySpecialities facilitySpecialities = (FacilitySpecialities) o;
    return Objects.equals(this.systemOfMedicineCode, facilitySpecialities.systemOfMedicineCode) &&
        Objects.equals(this.isSpecializationAvalaible, facilitySpecialities.isSpecializationAvalaible) &&
        Objects.equals(this.specialities, facilitySpecialities.specialities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systemOfMedicineCode, isSpecializationAvalaible, specialities);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacilitySpecialities {\n");
    sb.append("    systemOfMedicineCode: ").append(toIndentedString(systemOfMedicineCode)).append("\n");
    sb.append("    isSpecializationAvalaible: ").append(toIndentedString(isSpecializationAvalaible)).append("\n");
    sb.append("    specialities: ").append(toIndentedString(specialities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("systemOfMedicineCode");
    openapiFields.add("isSpecializationAvalaible");
    openapiFields.add("specialities");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FacilitySpecialities
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FacilitySpecialities.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FacilitySpecialities is not found in the empty JSON string", FacilitySpecialities.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FacilitySpecialities.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FacilitySpecialities` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("systemOfMedicineCode") != null && !jsonObj.get("systemOfMedicineCode").isJsonNull()) && !jsonObj.get("systemOfMedicineCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `systemOfMedicineCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("systemOfMedicineCode").toString()));
      }
      if ((jsonObj.get("isSpecializationAvalaible") != null && !jsonObj.get("isSpecializationAvalaible").isJsonNull()) && !jsonObj.get("isSpecializationAvalaible").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isSpecializationAvalaible` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isSpecializationAvalaible").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("specialities") != null && !jsonObj.get("specialities").isJsonNull() && !jsonObj.get("specialities").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `specialities` to be an array in the JSON string but got `%s`", jsonObj.get("specialities").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FacilitySpecialities.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FacilitySpecialities' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FacilitySpecialities> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FacilitySpecialities.class));

       return (TypeAdapter<T>) new TypeAdapter<FacilitySpecialities>() {
           @Override
           public void write(JsonWriter out, FacilitySpecialities value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FacilitySpecialities read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FacilitySpecialities given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FacilitySpecialities
   * @throws IOException if the JSON string is invalid with respect to FacilitySpecialities
   */
  public static FacilitySpecialities fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FacilitySpecialities.class);
  }

  /**
   * Convert an instance of FacilitySpecialities to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

