/*
 * PHR V3 Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.*;

/**
 * LoginOtpVerifyMobile200ResponseTokens
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-10T18:02:09.764020+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class LoginOtpVerifyMobile200ResponseTokens {
  public static final String SERIALIZED_NAME_EXPIRES_IN = "expiresIn";
  @SerializedName(SERIALIZED_NAME_EXPIRES_IN)
  @javax.annotation.Nullable
  private BigDecimal expiresIn;

  public static final String SERIALIZED_NAME_REFRESH_EXPIRES_IN = "refreshExpiresIn";
  @SerializedName(SERIALIZED_NAME_REFRESH_EXPIRES_IN)
  @javax.annotation.Nullable
  private BigDecimal refreshExpiresIn;

  public static final String SERIALIZED_NAME_REFRESH_TOKEN = "refreshToken";
  @SerializedName(SERIALIZED_NAME_REFRESH_TOKEN)
  @javax.annotation.Nullable
  private String refreshToken;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  @javax.annotation.Nullable
  private String token;

  public static final String SERIALIZED_NAME_SWITCH_PROFILE_ENABLED = "switchProfileEnabled";
  @SerializedName(SERIALIZED_NAME_SWITCH_PROFILE_ENABLED)
  @javax.annotation.Nullable
  private Boolean switchProfileEnabled;

  public LoginOtpVerifyMobile200ResponseTokens() {
  }

  public LoginOtpVerifyMobile200ResponseTokens expiresIn(@javax.annotation.Nullable BigDecimal expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * Get expiresIn
   * @return expiresIn
   */
  @javax.annotation.Nullable
  public BigDecimal getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(@javax.annotation.Nullable BigDecimal expiresIn) {
    this.expiresIn = expiresIn;
  }


  public LoginOtpVerifyMobile200ResponseTokens refreshExpiresIn(@javax.annotation.Nullable BigDecimal refreshExpiresIn) {
    this.refreshExpiresIn = refreshExpiresIn;
    return this;
  }

  /**
   * Get refreshExpiresIn
   * @return refreshExpiresIn
   */
  @javax.annotation.Nullable
  public BigDecimal getRefreshExpiresIn() {
    return refreshExpiresIn;
  }

  public void setRefreshExpiresIn(@javax.annotation.Nullable BigDecimal refreshExpiresIn) {
    this.refreshExpiresIn = refreshExpiresIn;
  }


  public LoginOtpVerifyMobile200ResponseTokens refreshToken(@javax.annotation.Nullable String refreshToken) {
    this.refreshToken = refreshToken;
    return this;
  }

  /**
   * Get refreshToken
   * @return refreshToken
   */
  @javax.annotation.Nullable
  public String getRefreshToken() {
    return refreshToken;
  }

  public void setRefreshToken(@javax.annotation.Nullable String refreshToken) {
    this.refreshToken = refreshToken;
  }


  public LoginOtpVerifyMobile200ResponseTokens token(@javax.annotation.Nullable String token) {
    this.token = token;
    return this;
  }

  /**
   * Get token
   * @return token
   */
  @javax.annotation.Nullable
  public String getToken() {
    return token;
  }

  public void setToken(@javax.annotation.Nullable String token) {
    this.token = token;
  }

  public LoginOtpVerifyMobile200ResponseTokens switchProfileEnabled(@javax.annotation.Nullable Boolean switchProfileEnabled) {
    this.switchProfileEnabled = switchProfileEnabled;
    return this;
  }

  /**
   * Get switchProfileEnabled
   * @return switchProfileEnabled
   */
  @javax.annotation.Nullable
  public Boolean getSwitchProfileEnabled() {
    return switchProfileEnabled;
  }

  public void setSwitchProfileEnabled(@javax.annotation.Nullable Boolean switchProfileEnabled) {
    this.switchProfileEnabled = switchProfileEnabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginOtpVerifyMobile200ResponseTokens loginOtpVerifyMobile200ResponseTokens = (LoginOtpVerifyMobile200ResponseTokens) o;
    return Objects.equals(this.expiresIn, loginOtpVerifyMobile200ResponseTokens.expiresIn) &&
        Objects.equals(this.refreshExpiresIn, loginOtpVerifyMobile200ResponseTokens.refreshExpiresIn) &&
        Objects.equals(this.refreshToken, loginOtpVerifyMobile200ResponseTokens.refreshToken) &&
        Objects.equals(this.token, loginOtpVerifyMobile200ResponseTokens.token) &&
        Objects.equals(this.switchProfileEnabled, loginOtpVerifyMobile200ResponseTokens.switchProfileEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiresIn, refreshExpiresIn, refreshToken, token, switchProfileEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginOtpVerifyMobile200ResponseTokens {\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    refreshExpiresIn: ").append(toIndentedString(refreshExpiresIn)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    switchProfileEnabled: ").append(toIndentedString(switchProfileEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("expiresIn");
    openapiFields.add("refreshExpiresIn");
    openapiFields.add("refreshToken");
    openapiFields.add("token");
    openapiFields.add("switchProfileEnabled");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LoginOtpVerifyMobile200ResponseTokens
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LoginOtpVerifyMobile200ResponseTokens.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LoginOtpVerifyMobile200ResponseTokens is not found in the empty JSON string", LoginOtpVerifyMobile200ResponseTokens.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LoginOtpVerifyMobile200ResponseTokens.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LoginOtpVerifyMobile200ResponseTokens` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("refreshToken") != null && !jsonObj.get("refreshToken").isJsonNull()) && !jsonObj.get("refreshToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refreshToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refreshToken").toString()));
      }
      if ((jsonObj.get("token") != null && !jsonObj.get("token").isJsonNull()) && !jsonObj.get("token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoginOtpVerifyMobile200ResponseTokens.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoginOtpVerifyMobile200ResponseTokens' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoginOtpVerifyMobile200ResponseTokens> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoginOtpVerifyMobile200ResponseTokens.class));

       return (TypeAdapter<T>) new TypeAdapter<LoginOtpVerifyMobile200ResponseTokens>() {
           @Override
           public void write(JsonWriter out, LoginOtpVerifyMobile200ResponseTokens value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LoginOtpVerifyMobile200ResponseTokens read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LoginOtpVerifyMobile200ResponseTokens given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LoginOtpVerifyMobile200ResponseTokens
   * @throws IOException if the JSON string is invalid with respect to LoginOtpVerifyMobile200ResponseTokens
   */
  public static LoginOtpVerifyMobile200ResponseTokens fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoginOtpVerifyMobile200ResponseTokens.class);
  }

  /**
   * Convert an instance of LoginOtpVerifyMobile200ResponseTokens to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

