/*
 * HFR APIs
 * The following are APIs hosted by HFR for public use.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * SpecialitiesRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-25T14:50:59.077868+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class SpecialitiesRequest {
  public static final String SERIALIZED_NAME_SYSTEM_OF_MEDICINE_CODE = "systemOfMedicineCode";
  @SerializedName(SERIALIZED_NAME_SYSTEM_OF_MEDICINE_CODE)
  @javax.annotation.Nullable
  private String systemOfMedicineCode;

  public SpecialitiesRequest() {
  }

  public SpecialitiesRequest systemOfMedicineCode(@javax.annotation.Nullable String systemOfMedicineCode) {
    this.systemOfMedicineCode = systemOfMedicineCode;
    return this;
  }

  /**
   * Get systemOfMedicineCode
   * @return systemOfMedicineCode
   */
  @javax.annotation.Nullable
  public String getSystemOfMedicineCode() {
    return systemOfMedicineCode;
  }

  public void setSystemOfMedicineCode(@javax.annotation.Nullable String systemOfMedicineCode) {
    this.systemOfMedicineCode = systemOfMedicineCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpecialitiesRequest specialitiesRequest = (SpecialitiesRequest) o;
    return Objects.equals(this.systemOfMedicineCode, specialitiesRequest.systemOfMedicineCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systemOfMedicineCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpecialitiesRequest {\n");
    sb.append("    systemOfMedicineCode: ").append(toIndentedString(systemOfMedicineCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("systemOfMedicineCode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SpecialitiesRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SpecialitiesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SpecialitiesRequest is not found in the empty JSON string", SpecialitiesRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SpecialitiesRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SpecialitiesRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("systemOfMedicineCode") != null && !jsonObj.get("systemOfMedicineCode").isJsonNull()) && !jsonObj.get("systemOfMedicineCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `systemOfMedicineCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("systemOfMedicineCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SpecialitiesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SpecialitiesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SpecialitiesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SpecialitiesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SpecialitiesRequest>() {
           @Override
           public void write(JsonWriter out, SpecialitiesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SpecialitiesRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SpecialitiesRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SpecialitiesRequest
   * @throws IOException if the JSON string is invalid with respect to SpecialitiesRequest
   */
  public static SpecialitiesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SpecialitiesRequest.class);
  }

  /**
   * Convert an instance of SpecialitiesRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

