/*
 * PHR V3 Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.abha.rest.client.model;

import com.google.gson.*;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.docq.abha.rest.client.JSON;
import in.docq.abha.rest.client.model.AbstractOpenApiSchema;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-10T18:02:09.764020+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class VerifyUser400Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(VerifyUser400Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!VerifyUser400Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'VerifyUser400Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);

            final Type typeInstanceListOtpVerifyMobile400ResponseInner = new TypeToken<List<OtpVerifyMobile400ResponseInner>>(){}.getType();
            final TypeAdapter<List<OtpVerifyMobile400ResponseInner>> adapterListOtpVerifyMobile400ResponseInner = (TypeAdapter<List<OtpVerifyMobile400ResponseInner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListOtpVerifyMobile400ResponseInner));
            final TypeAdapter<VerifyUser400ResponseAnyOf> adapterVerifyUser400ResponseAnyOf = gson.getDelegateAdapter(this, TypeToken.get(VerifyUser400ResponseAnyOf.class));

            final Type typeInstanceListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner = new TypeToken<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>>(){}.getType();
            final TypeAdapter<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>> adapterListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner = (TypeAdapter<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner));

            final Type typeInstanceListOtpVerifyMobile400ResponseInner2 = new TypeToken<List<OtpVerifyMobile400ResponseInner>>(){}.getType();
            final TypeAdapter<List<OtpVerifyMobile400ResponseInner>> adapterListOtpVerifyMobile400ResponseInner3 = (TypeAdapter<List<OtpVerifyMobile400ResponseInner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListOtpVerifyMobile400ResponseInner2));

            final Type typeInstanceListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner4 = new TypeToken<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>>(){}.getType();
            final TypeAdapter<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>> adapterListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner5 = (TypeAdapter<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner4));

            final Type typeInstanceListOtpVerifyMobile400ResponseInner6 = new TypeToken<List<OtpVerifyMobile400ResponseInner>>(){}.getType();
            final TypeAdapter<List<OtpVerifyMobile400ResponseInner>> adapterListOtpVerifyMobile400ResponseInner7 = (TypeAdapter<List<OtpVerifyMobile400ResponseInner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListOtpVerifyMobile400ResponseInner6));

            final Type typeInstanceListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner8 = new TypeToken<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>>(){}.getType();
            final TypeAdapter<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>> adapterListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner9 = (TypeAdapter<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner8));

            final Type typeInstanceListOtpVerifyMobile400ResponseInner10 = new TypeToken<List<OtpVerifyMobile400ResponseInner>>(){}.getType();
            final TypeAdapter<List<OtpVerifyMobile400ResponseInner>> adapterListOtpVerifyMobile400ResponseInner11 = (TypeAdapter<List<OtpVerifyMobile400ResponseInner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListOtpVerifyMobile400ResponseInner10));

            final Type typeInstanceListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner12 = new TypeToken<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>>(){}.getType();
            final TypeAdapter<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>> adapterListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner13 = (TypeAdapter<List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner12));

            return (TypeAdapter<T>) new TypeAdapter<VerifyUser400Response>() {
                @Override
                public void write(JsonWriter out, VerifyUser400Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `List<OtpVerifyMobile400ResponseInner>`
                    if (value.getActualInstance() instanceof List<?>) {
                        List<?> list = (List<?>) value.getActualInstance();
                        if (list.get(0) instanceof OtpVerifyMobile400ResponseInner) {
                            JsonArray array = adapterListOtpVerifyMobile400ResponseInner11.toJsonTree((List<OtpVerifyMobile400ResponseInner>)value.getActualInstance()).getAsJsonArray();
                            elementAdapter.write(out, array);
                            return;
                        }
                    }
                    // check if the actual instance is of the type `VerifyUser400ResponseAnyOf`
                    if (value.getActualInstance() instanceof VerifyUser400ResponseAnyOf) {
                        JsonElement element = adapterVerifyUser400ResponseAnyOf.toJsonTree((VerifyUser400ResponseAnyOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: List<OtpVerifyMobile400ResponseInner>, List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>, VerifyUser400ResponseAnyOf");
                }

                @Override
                public VerifyUser400Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize List<OtpVerifyMobile400ResponseInner>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                            OtpVerifyMobile400ResponseInner.validateJsonElement(element);
                        }
                        actualAdapter = adapterListOtpVerifyMobile400ResponseInner11;
                        VerifyUser400Response ret = new VerifyUser400Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<OtpVerifyMobile400ResponseInner> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<OtpVerifyMobile400ResponseInner>'", e);
                    }
                    // deserialize VerifyUser400ResponseAnyOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        VerifyUser400ResponseAnyOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterVerifyUser400ResponseAnyOf;
                        VerifyUser400Response ret = new VerifyUser400Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for VerifyUser400ResponseAnyOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'VerifyUser400ResponseAnyOf'", e);
                    }

                    throw new IOException(String.format("Failed deserialization for VerifyUser400Response: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public VerifyUser400Response() {
        super("anyOf", Boolean.FALSE);
    }

    public VerifyUser400Response(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("List<OtpVerifyMobile400ResponseInner>", List.class);
        schemas.put("VerifyUser400ResponseAnyOf", VerifyUser400ResponseAnyOf.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return VerifyUser400Response.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * List<OtpVerifyMobile400ResponseInner>, List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>, VerifyUser400ResponseAnyOf
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof OtpVerifyMobile400ResponseInner) {
                super.setActualInstance(instance);
                return;
            }
        }

        if (instance instanceof VerifyUser400ResponseAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be List<OtpVerifyMobile400ResponseInner>, List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>, VerifyUser400ResponseAnyOf");
    }

    /**
     * Get the actual instance, which can be the following:
     * List<OtpVerifyMobile400ResponseInner>, List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>, VerifyUser400ResponseAnyOf
     *
     * @return The actual instance (List<OtpVerifyMobile400ResponseInner>, List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>, VerifyUser400ResponseAnyOf)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<OtpVerifyMobile400ResponseInner>`. If the actual instance is not `List<OtpVerifyMobile400ResponseInner>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<OtpVerifyMobile400ResponseInner>`
     * @throws ClassCastException if the instance is not `List<OtpVerifyMobile400ResponseInner>`
     */
    public List<OtpVerifyMobile400ResponseInner> getListOtpVerifyMobile400ResponseInner() throws ClassCastException {
        return (List<OtpVerifyMobile400ResponseInner>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `VerifyUser400ResponseAnyOf`. If the actual instance is not `VerifyUser400ResponseAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `VerifyUser400ResponseAnyOf`
     * @throws ClassCastException if the instance is not `VerifyUser400ResponseAnyOf`
     */
    public VerifyUser400ResponseAnyOf getVerifyUser400ResponseAnyOf() throws ClassCastException {
        return (VerifyUser400ResponseAnyOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>`. If the actual instance is not `List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>`
     * @throws ClassCastException if the instance is not `List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>`
     */
    public List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner> getListSearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner() throws ClassCastException {
        return (List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to VerifyUser400Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with List<OtpVerifyMobile400ResponseInner>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
                OtpVerifyMobile400ResponseInner.validateJsonElement(element);
            }
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<OtpVerifyMobile400ResponseInner> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with VerifyUser400ResponseAnyOf
        try {
            VerifyUser400ResponseAnyOf.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for VerifyUser400ResponseAnyOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format("The JSON string is invalid for VerifyUser400Response with anyOf schemas: List<OtpVerifyMobile400ResponseInner>, List<SearchAuthMethodsAbhaaddress400ResponseAnyOf1Inner>, VerifyUser400ResponseAnyOf. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of VerifyUser400Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of VerifyUser400Response
     * @throws IOException if the JSON string is invalid with respect to VerifyUser400Response
     */
    public static VerifyUser400Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, VerifyUser400Response.class);
    }

    /**
     * Convert an instance of VerifyUser400Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

