/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.docq.keycloak.rest.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import in.docq.keycloak.rest.client.JSON;

/**
 * SocialLinkRepresentation
 */
@javax.annotation.Generated(value = "in.docq.keycloak.rest.codegen.languages.JavaClientCodegen", date = "2025-02-08T16:05:02.219423+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
public class SocialLinkRepresentation {
  public static final String SERIALIZED_NAME_SOCIAL_PROVIDER = "socialProvider";
  @SerializedName(SERIALIZED_NAME_SOCIAL_PROVIDER)
  @javax.annotation.Nullable
  private String socialProvider;

  public static final String SERIALIZED_NAME_SOCIAL_USER_ID = "socialUserId";
  @SerializedName(SERIALIZED_NAME_SOCIAL_USER_ID)
  @javax.annotation.Nullable
  private String socialUserId;

  public static final String SERIALIZED_NAME_SOCIAL_USERNAME = "socialUsername";
  @SerializedName(SERIALIZED_NAME_SOCIAL_USERNAME)
  @javax.annotation.Nullable
  private String socialUsername;

  public SocialLinkRepresentation() {
  }

  public SocialLinkRepresentation socialProvider(@javax.annotation.Nullable String socialProvider) {
    this.socialProvider = socialProvider;
    return this;
  }

  /**
   * Get socialProvider
   * @return socialProvider
   */
  @javax.annotation.Nullable
  public String getSocialProvider() {
    return socialProvider;
  }

  public void setSocialProvider(@javax.annotation.Nullable String socialProvider) {
    this.socialProvider = socialProvider;
  }


  public SocialLinkRepresentation socialUserId(@javax.annotation.Nullable String socialUserId) {
    this.socialUserId = socialUserId;
    return this;
  }

  /**
   * Get socialUserId
   * @return socialUserId
   */
  @javax.annotation.Nullable
  public String getSocialUserId() {
    return socialUserId;
  }

  public void setSocialUserId(@javax.annotation.Nullable String socialUserId) {
    this.socialUserId = socialUserId;
  }


  public SocialLinkRepresentation socialUsername(@javax.annotation.Nullable String socialUsername) {
    this.socialUsername = socialUsername;
    return this;
  }

  /**
   * Get socialUsername
   * @return socialUsername
   */
  @javax.annotation.Nullable
  public String getSocialUsername() {
    return socialUsername;
  }

  public void setSocialUsername(@javax.annotation.Nullable String socialUsername) {
    this.socialUsername = socialUsername;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SocialLinkRepresentation socialLinkRepresentation = (SocialLinkRepresentation) o;
    return Objects.equals(this.socialProvider, socialLinkRepresentation.socialProvider) &&
        Objects.equals(this.socialUserId, socialLinkRepresentation.socialUserId) &&
        Objects.equals(this.socialUsername, socialLinkRepresentation.socialUsername);
  }

  @Override
  public int hashCode() {
    return Objects.hash(socialProvider, socialUserId, socialUsername);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SocialLinkRepresentation {\n");
    sb.append("    socialProvider: ").append(toIndentedString(socialProvider)).append("\n");
    sb.append("    socialUserId: ").append(toIndentedString(socialUserId)).append("\n");
    sb.append("    socialUsername: ").append(toIndentedString(socialUsername)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("socialProvider");
    openapiFields.add("socialUserId");
    openapiFields.add("socialUsername");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SocialLinkRepresentation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SocialLinkRepresentation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SocialLinkRepresentation is not found in the empty JSON string", SocialLinkRepresentation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SocialLinkRepresentation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SocialLinkRepresentation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("socialProvider") != null && !jsonObj.get("socialProvider").isJsonNull()) && !jsonObj.get("socialProvider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `socialProvider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("socialProvider").toString()));
      }
      if ((jsonObj.get("socialUserId") != null && !jsonObj.get("socialUserId").isJsonNull()) && !jsonObj.get("socialUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `socialUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("socialUserId").toString()));
      }
      if ((jsonObj.get("socialUsername") != null && !jsonObj.get("socialUsername").isJsonNull()) && !jsonObj.get("socialUsername").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `socialUsername` to be a primitive type in the JSON string but got `%s`", jsonObj.get("socialUsername").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SocialLinkRepresentation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SocialLinkRepresentation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SocialLinkRepresentation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SocialLinkRepresentation.class));

       return (TypeAdapter<T>) new TypeAdapter<SocialLinkRepresentation>() {
           @Override
           public void write(JsonWriter out, SocialLinkRepresentation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SocialLinkRepresentation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SocialLinkRepresentation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SocialLinkRepresentation
   * @throws IOException if the JSON string is invalid with respect to SocialLinkRepresentation
   */
  public static SocialLinkRepresentation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SocialLinkRepresentation.class);
  }

  /**
   * Convert an instance of SocialLinkRepresentation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

